name: Install
description: Install Node.js and dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm

    - name: Install
      run: npm ci
      shell: bash
