name: Install
description: Install Node.js and dependencies

inputs:
  workspace:
    default: ''
    description: 'Workspace to run npm ci in'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: npm

    - name: Install
      shell: bash
      run: npm ci ${{ inputs.workspace != '' && format('--workspace={0}', inputs.workspace) || '' }}
