name: Verify
description: Type-check, lint and test

inputs:
  codecov-token:
    description: Codecov token for uploading coverage reports
    required: true

runs:
  using: composite
  steps:
    - name: Check types
      shell: bash
      run: npm run type-check

    - name: ESLint
      shell: bash
      run: npm run lint

    - name: Prettier
      shell: bash
      run: npm run lint:format

    - name: Stylelint
      shell: bash
      run: npm run lint:style

    - name: Vitest
      shell: bash
      run: npm run test:coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov-token }}
        slug: tu4mo/pizzagram
