name: Verify
description: Type-check and lint

runs:
  using: composite
  steps:
    - name: Check types
      shell: bash
      run: npm run type-check

    - name: Lint
      shell: bash
      run: |
        npm run lint:oxlint
        npm run lint
        npm run lint:format
        npm run lint:style
