name: Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: production

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/install

      - name: Check types
        run: npm run type-check

      - name: Lint
        run: |
          npm run lint
          npm run lint:format

      - name: Build
        run: npm run build

      - name: Delete callable functions
        run: |
          npx firebase functions:delete verifyImage --force --token ${{ secrets.FIREBASE_TOKEN }}
          npx firebase functions:delete registerUser --force --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy
        if: always()
        run: npx firebase deploy --force --token ${{ secrets.FIREBASE_TOKEN }}
