name: Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: production

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js and dependencies
        uses: ./.github/actions/install

      - name: Check types
        run: npm run type-check

      - name: Lint
        run: |
          npm run lint
          npm run lint:format

      - name: Build
        run: npm run build

      - name: Delete callable functions
        run: |
          npx firebase functions:delete sharePost --force --token ${{ secrets.FIREBASE_TOKEN }}
          npx firebase functions:delete registerUser --force --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy
        if: always()
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PIZZAGRAM_CC }}
          projectId: pizzagram-cc
          channelId: live
