name: Production

on:
  push:
    branches:
      - master

concurrency: production

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Check types
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Delete callable functions
        run: |
          npx firebase functions:delete verifyimage --force --token ${{ secrets.FIREBASE_TOKEN }}
          npx firebase functions:delete registerUser --force --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy
        if: always()
        run: npx firebase deploy --force --token ${{ secrets.FIREBASE_TOKEN }}
