name: Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: production

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js and dependencies
        uses: ./.github/actions/install

      - name: Type-check and lint
        uses: ./.github/actions/verify

      - name: Build
        run: npm run build

      - name: Delete callable functions
        continue-on-error: true
        run: |
          npx firebase functions:delete onSharePostCall --force --token ${{ secrets.FIREBASE_TOKEN }}
          npx firebase functions:delete onRegisterUserCall --force --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy
        if: success() || failure()
        run: npx firebase deploy --force --token ${{ secrets.FIREBASE_TOKEN }}

  test:
    name: E2E tests
    needs: release
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js and dependencies
        uses: ./.github/actions/install

      - name: Get Playwright version
        id: playwright-version
        run: |
          echo version=$(jq -r '.devDependencies["@playwright/test"]' ./e2e/package.json) >> $GITHUB_OUTPUT

      # - name: Cache Playwright browsers
      #   uses: actions/cache@v4
      #   id: playwright-cache
      #   with:
      #     path: ~/.cache/ms-playwright
      #     key: playwright-browsers-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}
      - name: Install Playwright browsers
        run: npx playwright install --with-deps webkit
        # if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Run Playwright tests
        run: npm test --workspace e2e
        env:
          PLAYWRIGHT_FIREBASE_APPCHECK_DEBUG_TOKEN: ${{ secrets.PLAYWRIGHT_FIREBASE_APPCHECK_DEBUG_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
